ui: tape
browsers:
  - name: microsoftedge
    version: latest
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 8..latest
  - name: opera
    version: latest
  - name: iphone
    version: latest
  - name: android
    version: latest
